config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'profile', to: 'pages#profile'
  # Generic syntax:
  # verb 'path', to: 'controller#action', as: :route_name
  resources :users
  resources :degrees
  resources :experiences
  resources :courses
  resources :companies do
    resources :jobs do
      # resources :favorites
    end
  end
  post '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'favorites#create', :as => :favorite_create

  get '/companies/:company_id/jobs/:id/candidates', to: 'jobs#candidates', :as => :job_candidates
  get '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'jobs#candidate', :as => :job_candidate

  get '/companies/:company_id/jobs/:id/favorites', to: 'jobs#favorites', :as => :job_favorites
end

app/models/job.rb
class Job < ApplicationRecord
  JOBPOSITIONS = ["Açougueira(o)", "Ajudante", "Analista", "Assistente", "Atendente", "Auxiliar",
                  "Balconista", "Barista", "Barman", "Cabeleireira(o)", "Caixa", "Carpinteira(o)",
                  "Consultor(a)", "Coordenador(a)", "Copeira(o)", "Corretor(a)", "Cozinheira(o)",
                  "Desenvolvedor(a)", "Diretor(a)", "Eletricista", "Empregada(o) Doméstica(o)",
                  "Encanador(a)", "Entregador(a) ou Motoboy", "Especialista", "Estagiária(o)",
                  "Esteticista", "Estoquista", "Faxineira(o)", "Fiscal", "Frentista", "Garçom / Garçonete",
                  "Gerente", "Inspetor(a)", "Instalador(a)", "Jardineira(o)", "Lavador(a) ou Limpador(a)",
                  "Manobrista", "Maquiadora(o)", "Mecânica(o)", "Motorista", "Operador(a)",
                  "Operador(a) de Máquinas", "Padeira(o)", "Pedreira(o)", "Peixeira(o)", "Pintor(a)",
                  "Pizzaiola(o)", "Porteira(o)", "Promotor(a)", "Recepcionista", "Reparador(a)",
                  "Repositor(a)", "Representante", "Secretária(o)", "Segurança", "Supervisor(a)",
                  "Sushiman", "Técnica(o)", "Terapeuta", "Trainee", "Vendedor(a)",
                  "Zelador(a)"].freeze
  JOBSECTORS = ["Administrativo", "Atendimento e Recepção", "Contábil", "Comercial / Marketing",
                "Departamento Pessoal", "Estoque", "Financeiro", "Manutenção", "Operacional",
                "Planejamento e Estratégia", "Produção", "Projetos", "Recursos Humanos", "Serviços Gerais",
                "Suporte e Apoio Operacional", "Transporte e Logística", "Vendas"].freeze
  SALARYRANGES = ["998 a 1.500", "1.501 a 2.000", "2.000 a 3.000", "3.001 a 4.000",
                  "4.001 a 6.000", "6.001 a 8.000", "8.001 a 10.000", "acima de 10.000",
                  "a combinar"].freeze
  belongs_to :company
  has_many :favorites, :dependent => :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :candidates, :favorites]
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
  end

  def index
    @company = Company.find(params[:company_id])
    @jobs = policy_scope(Job)
    authorize @company.jobs
  end

  def new
    @company = Company.find(params[:company_id])
    @job = Job.new(company: @company)
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    authorize @job
    @job.company = Company.find(params[:company_id])
    if @job.save
      redirect_to company_jobs_path(@job.company)
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:company_id])
    @job.company = @company
  end

  def update
    @company = Company.find(params[:company_id])
    @job.company = @company
    if @job.update(job_params)
      redirect_to company_jobs_path(@job.company)
    else
      render :update
    end
  end

  def destroy
    @job.destroy
    redirect_to profile_path
  end

  # def candidates
  #   job = Job.find(params[:id])
  #   @filtered_candidates = User.initial_filter(job)
  #   candidates_hash = {}
  #   match_potential = 0
  #   @filtered_candidates.each do |candidate|
  #     candidate.experiences.each do |experience|
  #       match_potential -= 70 if experience.level.include?('mais de 5 anos')
  #       match_potential -= 60 if experience.level.include?('5 anos')
  #       match_potential -= 50 if experience.level.include?('4 anos')
  #       match_potential -= 40 if experience.level.include?('3 anos')
  #       match_potential -= 30 if experience.level.include?('2 anos')
  #       match_potential -= 20 if experience.level.include?('1 ano')
  #       match_potential -= 10 if experience.level.include?('menos de 1 ano')
  #     end
  #     candidate.degrees.each do |degree|
  #       match_potential -= 3 if degree.level.include?('Mestrado') || degree.level.include?('Doutorado')
  #       match_potential -= 2 if degree.level.include?('Pós-graduação') || degree.level.include?('Ensino Superior')
  #       match_potential -= 1 if degree.level.include?('Ensino Médio')
  #     end
  #     candidates_hash[candidate] = match_potential
  #     match_potential = 0
  #   end
  #   @all_candidates = candidates_hash.sort_by { |key, value| value }
  # end

  def candidates
    job = Job.find(params[:id])
    @filtered_candidates = User.initial_filter(job)
    candidates_hash = {}
    match_potential = 0
    @filtered_candidates.each do |candidate|
      candidate.experiences.each do |experience|
        match_potential -= 70 if experience.level.include?('mais de 5 anos')
        match_potential -= 60 if experience.level.include?('5 anos')
        match_potential -= 50 if experience.level.include?('4 anos')
        match_potential -= 40 if experience.level.include?('3 anos')
        match_potential -= 30 if experience.level.include?('2 anos')
        match_potential -= 20 if experience.level.include?('1 ano')
        match_potential -= 10 if experience.level.include?('menos de 1 ano')
      end
      candidate.degrees.each do |degree|
        match_potential -= 3 if degree.level.include?('Mestrado') || degree.level.include?('Doutorado')
        match_potential -= 2 if degree.level.include?('Pós-graduação') || degree.level.include?('Ensino Superior')
        match_potential -= 1 if degree.level.include?('Ensino Médio')
      end
      candidates_hash[candidate] = match_potential
      match_potential = 0
    end
    @all_candidates = candidates_hash.sort_by { |key, value| value }
  end

  def candidate
    @candidate = User.find(params[:user_id])
    authorize current_user
  end

  def favorites
    job = Job.find(params[:id])
    @favorite_candidates = User.favorite_initial_filter(job)
  end

  private

  def set_job
    @job = Job.find(params[:id])
    authorize @job
  end

  def job_params
    params.require(:job).permit(:title, :level, :sector, :salary_range,
                                :benefit, :description, :start_time, :end_time,
                                :education_requirement)
  end
end

app/views/jobs/_candidate-courses.html.erb
<h5>Cursos:</h5>

<div class="degrees-box">
  <% @candidate.courses.each do |course| %>
    <div class="degree-box">
      <p><%= course.category %>: <%= course.school_name %></p>
      <p>Descrição: <%=  course.description %></p>
      <% if course.complete == "1" %>
        <p>Completo</p>
      <% else %>
        <p>Incompleto</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/jobs/_candidate-degrees.html.erb
<h5>Formação educacional:</h5>

<div class="degrees-box">
  <% @candidate.degrees.each do |degree| %>
    <div class="degree-box">
      <p><%= degree.level %>
        <% if degree.complete == "1" %>
          Completo
        <% else %>
          Incompleto
        <% end %>
      </p>
      <p>Instituição: <%= degree.school_name %></p>
        <% if degree.field.empty? %>
        <% else %>
         <p>Curso: <%= degree.field %></p>
        <% end %>
    </div>
  <% end %>
</div>

app/views/jobs/_candidate-details.html.erb
<h5><%= @candidate.first_name %> <%= @candidate.last_name %></h5>

<div class="degrees-box">
  <div class="degree-box">
    <p>CPF: <%= @candidate.cpf %></p>
    <p><i class="fas fa-envelope"></i> <%= @candidate.email %></p>
    <p><i class="fas fa-phone"></i> <%= @candidate.phone %></p>
    <p><i class="fas fa-home"></i> <%= @candidate.address %></p>
    <% if @candidate.address_complement.nil? %>
    <% else %>
     <p>Complemento: <%= @candidate.address_complement %></p>
    <% end %>
  </div>
</div>

app/views/jobs/_candidate-experiences.html.erb
<h5>Experiência profissional:</h5>

<div class="degrees-box">
  <% @candidate.experiences.each do |experience| %>
    <div class="degree-box">
      <p>Empresa: <%= experience.company_name %> (<%= experience.company_sector %>)</p>
      <p>Cargo: <%= experience.title %></p>
      <p>Área: <%= experience.sector %></p>
      <p>Descrição: <%= experience.description %></p>
      <p>Tempo na empresa: <%= experience.level %></p>
    </div>
  <% end %>
</div>

app/views/jobs/candidate.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="profile-box">

    <%= render 'candidate-details' %>

    <% if @candidate.experiences.count >= 1 %>
      <%= render 'candidate-experiences', experiences: @candidate.experiences %>
    <% else %>
    <% end %>

    <% if @candidate.degrees.count >= 1 %>
      <%= render 'candidate-degrees', degrees: @candidate.degrees %>
    <% else %>
    <% end %>

    <% if @candidate.courses.count >= 1 %>
      <%= render 'candidate-courses', courses: @candidate.courses %>
    <% else %>
    <% end %>

    <div class="favorite-back-box">
      <%#= link_to "Gostei!", profile_path, class: "btn btn-primary btn-sm" %>
      <%= link_to "Gostei!", favorite_create_path,
            method: :post, class: "btn btn-primary btn-sm" %>
      <%#= link_to "Gostei!", company_job_favorites_path(@job.company_id, @job), method: :post, class: "btn btn-primary btn-sm" %>
      <%#= link_to "Gostei!", company_job_favorites_path(@job.company_id, @job), method: :post, class: "btn btn-primary" %>
      <%#= link_to "Gostei!", company_job_favorites_path, method: :post, class: "btn btn-primary" %>
      <%= link_to "Voltar", :back, class: "btn btn-tertiary btn-sm" %>
    </div>

  </div>
</div>

app/views/jobs/candidates.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="profile-box">

    <h5>Candidatos para <%= @job.title %>:</h5>

    <div class="degrees-box">
      <% @all_candidates.each do |candidate| %>

        <% if candidate[1] <= 0 %>
          <div class="degree-box">
            <p>Nome: <%= candidate[0].first_name %> <%= candidate[0].last_name %> </p>
            <p>Experiência como <%= candidate[0].experiences[0].title %>: <%= candidate[0].experiences[0].level %> </p>
            <p>Diploma: <%= candidate[0].degrees[0].level %> </p>
            <div class="complete-profile-box">
              <%= link_to "Perfil completo", job_candidate_path(@job.company_id, @job, candidate[0].id), class: "btn btn-secondary btn-sm" %>
            </div>
          </div>
        <% else %>
        <% end %>

      <% end %>
    </div>

    <br>
    <%= link_to "Voltar", company_jobs_path, class: "btn btn-tertiary btn-sm" %>

  </div>
</div>

app/views/jobs/edit.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="form-box">

    <h5>Editar vaga:</h5>

    <%= simple_form_for [@company, @job] do |f| %>
       <%= f.input :title,
                   required: true,
                   collection: Job::JOBPOSITIONS,
                   :label => "Cargo:" %>
       <%= f.input :sector,
                   required: true,
                   collection: Job::JOBSECTORS,
                   :label => "Setor do cargo:" %>
       <%= f.input :level,
                   required: true,
                   collection: Experience::EXPERIENCELEVELS,
                   :label => "Experiência desejada:" %>
       <%= f.input :education_requirement,
                   required: true,
                   collection: Degree::DEGREELEVELS,
                   :label => "Educação desejada:" %>
       <%= f.input :salary_range,
                   required: true,
                   collection: Job::SALARYRANGES,
                   :label => "Faixa salarial:" %>
       <%= f.input :benefit,
                   hint: "VT, VR, seguro saúde, etc.",
                   :label => "Benefícios:" %>
       <%= f.input :description,
                   hint: "Breve descrição das atividades",
                   :label => "Descrição:" %>

    <div class="form-actions">
      <%= f.submit class: 'btn btn-primary', value: "Confirmar" %>
    </div>
  <% end %>
      <br>
      <%= link_to "Voltar", profile_path, class: "btn btn-tertiary btn-sm" %>
      <br>
      <% if policy(@job).destroy? %>
        <%= link_to "Deletar esta vaga", company_job_path(@job),
            method: :delete, class: "edit-remove" %>
      <% end %>
  </div>
</div>

app/views/jobs/favorites.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="profile-box">

    <h5>Favoritos para <%= @job.title %>:</h5>

    <div class="degrees-box">
      <% @favorite_candidates.each do |candidate| %>

        <div class="degree-box">
          <p>Nome: <%= candidate.first_name %> <%= candidate.last_name %> </p>
          <p>Experiência como <%#= candidate.experiences.title %>: <%#= candidate.experiences.level %> </p>
          <p>Diploma: <%#= candidate.degrees.level %> </p>
          <div class="complete-profile-box">
            <%= link_to "Perfil completo", job_candidate_path(@job.company_id, @job, candidate.id), class: "btn btn-secondary btn-sm" %>
          </div>
        </div>

      <% end %>
    </div>

    <br>
    <%= link_to "Voltar", company_jobs_path, class: "btn btn-tertiary btn-sm" %>

  </div>
</div>

app/views/jobs/index.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="profile-box">

    <%= link_to "Criar vaga", new_company_job_path(@company, @job), class: "btn btn-create-job" %>

    <h5>Vagas <%= @company.name %>:</h5>

    <div class="degrees-box">
      <% @company.jobs.each do |job| %>
        <div class="degree-box">
          <p>Cargo: <%= job.title %> </p>
          <p>Setor: <%= job.sector %></p>
          <p>Experiência desejada: <%= job.level %></p>
          <p>Educação desejada: <%= job.education_requirement %></p>
          <p>Faixa salarial: <%= job.salary_range %></p>
          <p>Benefícios: <%= job.benefit %></p>
          <p>Descrição: <%= job.description %></p>

          <div class="edit-box">
          <!-- <div class="edit-create-box"> -->
            <!-- comment the div above and the button below, and uncomment the div edit box before git add -->
            <%#= link_to "Candidatos", job_candidates_path(@company, job), class: "btn btn-sm btn-candidates" %>
            <%= link_to "Editar", edit_company_job_path(@company, job), class: "edit-remove" %>
          </div>

          <!-- <div class="edit-create-box"> -->
            <%#= link_to "Favoritos", job_favorites_path(@company, job), class: "btn btn-sm btn-candidates" %>
          <!-- </div> -->

        </div>
      <% end %>
    </div>

    <br>
    <%= link_to "Voltar", profile_path, class: "btn btn-tertiary btn-sm" %>

  </div>
</div>

app/views/jobs/new.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="form-box">

   <h5>Criar vaga:</h5>

   <%= simple_form_for [@company, @job] do |f| %>
     <%= f.input :title,
                 required: true,
                 collection: Job::JOBPOSITIONS,
                 :label => "Cargo:" %>
     <%= f.input :sector,
                 required: true,
                 collection: Job::JOBSECTORS,
                 :label => "Setor do cargo:" %>
     <%= f.input :level,
                 required: true,
                 collection: Experience::EXPERIENCELEVELS,
                 :label => "Experiência desejada:" %>
     <%= f.input :education_requirement,
                 required: true,
                 collection: Degree::DEGREELEVELS,
                 :label => "Educação desejada:" %>
     <%= f.input :salary_range,
                 required: true,
                 collection: Job::SALARYRANGES,
                 :label => "Faixa salarial:" %>
     <%= f.input :benefit,
                 hint: "VT, VR, seguro saúde, etc.",
                 :label => "Benefícios:" %>
     <%= f.input :description,
                 hint: "Breve descrição das atividades",
                 :label => "Descrição:" %>

   <div class="form-actions">
     <%= f.submit class: 'btn btn-primary', value: "Confirmar" %>
   </div>
   <% end %>

   <p>Você pode criar mais vagas depois se quiser.</p>

  </div>
</div>