config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'profile', to: 'pages#profile'
  # Generic syntax:
  # verb 'path', to: 'controller#action', as: :route_name
  resources :users
  resources :degrees
  resources :experiences
  resources :courses
  resources :companies do
    resources :jobs do
      # resources :favorites
    end
  end
  post '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'favorites#create', :as => :favorite_create

  get '/companies/:company_id/jobs/:id/candidates', to: 'jobs#candidates', :as => :job_candidates
  get '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'jobs#candidate', :as => :job_candidate

  get '/companies/:company_id/jobs/:id/favorites', to: 'jobs#favorites', :as => :job_favorites
end

app/models/degree.rb
class Degree < ApplicationRecord
  DEGREELEVELS = ["Ensino Fundamental", "Ensino Médio", "Ensino Superior",
                  "Pós-graduação", "Mestrado", "Doutorado"].freeze
  belongs_to :user
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
  end

  def index
    @degrees = policy_scope(Degree)
  end

  def new
    @degree = Degree.new
    authorize @degree
  end

  def create
    @degree = Degree.new(degree_params)
    @degree.user = current_user
    authorize @degree
    if @degree.save
      if current_user.degrees.count == 1
        redirect_to new_experience_path
      else
        redirect_to profile_path
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    @degree.user = current_user
    if @degree.update(degree_params)
      redirect_to profile_path
    else
      render :update
    end
  end

  def destroy
    @degree.destroy
    redirect_to profile_path
  end

  private

  def set_degree
    @degree = Degree.find(params[:id])
    authorize @degree
  end

  def degree_params
    params.require(:degree).permit(:level, :school_name, :field, :complete)
  end
end

app/views/degrees/edit.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="form-box">

    <h5>Editar diploma:</h5>

    <%= simple_form_for(@degree) do |f| %>
      <%= f.error_notification %>

      <%= f.input :level, required: true, collection: Degree::DEGREELEVELS, :label => "Nível de escolaridade:" %>
      <%= f.input :school_name, required: true, :label => "Nome da escola/instituição:" %>
      <%= f.input :field, hint: "Apenas para Ensino Superior", :label => "Curso:" %>
      <%= f.input :complete, as: :boolean, :label => "Completo?" %>

      <div class="form-actions">
        <%= f.submit class: 'btn btn-primary', value: "Confirmar" %>
      </div>
    <% end %>
      <br>
      <%= link_to "Voltar", profile_path, class: "btn btn-tertiary btn-sm" %>
      <br>
      <% if policy(@degree).destroy? %>
        <%= link_to "Deletar este diploma", degree_path(@degree),
            method: :delete, class: "edit-remove" %>
      <% end %>
  </div>
</div>

app/views/degrees/new.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="form-box">

   <h5>Incluir diploma:</h5>

   <%= simple_form_for(@degree) do |f| %>
     <%= f.input :level, required: true, collection: Degree::DEGREELEVELS, :label => "Nível de escolaridade:" %>
     <%= f.input :school_name, required: true, :label => "Nome da escola/instituição:" %>
     <%= f.input :field, hint: "Apenas para Ensino Superior", :label => "Curso:" %>
     <%= f.input :complete, as: :boolean, :label => "Completo?" %>

   <div class="form-actions">
     <%= f.submit class: 'btn btn-primary', value: "Incluir" %>
   </div>
   <% end %>

   <p>Você pode incluir mais diplomas depois se quiser.</p>

  </div>
</div>