config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'profile', to: 'pages#profile'
  # Generic syntax:
  # verb 'path', to: 'controller#action', as: :route_name
  resources :users
  resources :degrees
  resources :experiences
  resources :courses
  resources :companies do
    resources :jobs do
      # resources :favorites
    end
  end
  post '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'favorites#create', :as => :favorite_create

  get '/companies/:company_id/jobs/:id/candidates', to: 'jobs#candidates', :as => :job_candidates
  get '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'jobs#candidate', :as => :job_candidate

  get '/companies/:company_id/jobs/:id/favorites', to: 'jobs#favorites', :as => :job_favorites
end

app/views/pages/_user-companies.html.erb
<h5>Empresas:</h5>

<div class="degrees-box">
  <% @companies.each do |company| %>
    <div class="degree-box">

      <div class="complete-company-box">
        <% if company.company_incomplete? %>
          <h5>Você precisa completar o perfil dessa empresa para que possamos te conectar com os candidatos.</h5>
          <%= link_to "Completar empresa", edit_company_path(company), class: "btn btn-primary btn-complete-company" %>
        <% else %>
        <% end %>
      </div>

      <p style="font-weight: 900"><%= company.name %> </p>
      <p>Setor: <%= company.sector %></p>
      <p><i class="fas fa-phone"></i> <%= company.phone %></p>
      <p><i class="fas fa-home"></i> <%= company.address %></p>
      <% if company.address_complement.nil? %>
      <% else %>
       <p>Complemento: <%= company.address_complement %></p>
      <% end %>
      <div class="edit-create-box">
        <%= link_to "Vagas", company_jobs_path(company), class: "btn btn-create-job" %>
        <%= link_to "Editar", edit_company_path(company), class: "edit-remove" %>
      </div>

    </div>
  <% end %>
</div>

<%= link_to "Incluir empresa", new_company_path, class: "btn btn-secondary btn-sm" %>

app/views/pages/_user-courses.html.erb
<h5>Cursos:</h5>

<div class="degrees-box">
  <% @courses.each do |course| %>
    <div class="degree-box">
      <p><%= course.category %>: <%= course.school_name %></p>
      <p>Descrição: <%=  course.description %></p>
      <% if course.complete == "1" %>
        <p>Completo</p>
      <% else %>
        <p>Incompleto</p>
      <% end %>
      <div class="edit-box">
        <%= link_to "Editar", edit_course_path(course), class: "edit-remove" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Incluir curso", new_course_path, class: "btn btn-secondary btn-sm" %>

app/views/pages/_user-degrees.html.erb
<h5>Formação educacional:</h5>

<div class="degrees-box">
  <% @degrees.each do |degree| %>
    <div class="degree-box">
      <p><%= degree.level %>
        <% if degree.complete == "1" %>
          Completo
        <% else %>
          Incompleto
        <% end %>
      </p>
      <p>Instituição: <%= degree.school_name %></p>
        <% if degree.field.empty? %>
        <% else %>
         <p>Curso: <%= degree.field %></p>
        <% end %>
      <div class="edit-box">
        <%= link_to "Editar", edit_degree_path(degree), class: "edit-remove" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Incluir diploma", new_degree_path, class: "btn btn-secondary btn-sm" %>

app/views/pages/_user-details.html.erb
<h5>Informações pessoais:</h5>

<div class="degrees-box">
  <div class="degree-box">
    <p style="font-weight: 900"> <%= current_user.first_name %> <%= current_user.last_name %></p>
    <p>CPF: <%= current_user.cpf %></p>
    <p><i class="fas fa-envelope"></i> <%= current_user.email %></p>
    <p><i class="fas fa-phone"></i> <%= current_user.phone %></p>
    <p><i class="fas fa-home"></i> <%= current_user.address %></p>
    <% if current_user.address_complement.nil? %>
    <% else %>
     <p>Complemento: <%= current_user.address_complement %></p>
    <% end %>
    <div class="edit-box">
      <%= link_to "Editar", edit_user_registration_path, class: "edit-remove" %>
    </div>
  </div>
</div>

app/views/pages/_user-experiences.html.erb
<h5>Experiência profissional:</h5>

<div class="degrees-box">
  <% @experiences.each do |experience| %>
    <div class="degree-box">
      <p>Empresa: <%= experience.company_name %> (<%= experience.company_sector %>)</p>
      <p>Cargo: <%= experience.title %></p>
      <p>Área: <%= experience.sector %></p>
      <p>Descrição: <%= experience.description %></p>
      <p>Tempo na empresa: <%= experience.level %></p>
      <div class="edit-box">
        <%= link_to "Editar", edit_experience_path(experience), class: "edit-remove" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Incluir experiência", new_experience_path, class: "btn btn-secondary btn-sm" %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.5) 0%, rgba(0,36,61,0.5) 50%), url('<%= image_path "fabio-spinelli-695744.jpg" %>');" alt="VagaZap: Vagas de emprego na palma da sua mão.">
  <div class="container row">
    <div class="col-md-7 col-lg-8">
    </div>
    <div class="col-md-5 col-lg-4 banner-content">
      <div>
        <h5>Vagas de emprego na palma da sua mão. Grátis!</h5>
      </div>
      <% if user_signed_in? %>
        <h6>Ainda não foi possível encontrar uma vaga com o seu perfil.</h6>
        <!-- <h6>Obrigado por se cadastrar! As vagas estarão disponíveis a partir de 01 de Junho.</h6> -->
        <!-- <a href="mailto:marcus.maione@vagazap.com">Dúvidas ou sugestões: marcus.maione@vagazap.com</a> -->

        <!-- Habilitar botão quando tiver vagas -->
        <%#= link_to 'Vagas disponíveis', root_path, class: "btn btn-primary" %>
      <% else %>
        <%= link_to 'Como funciona', '#how', class: "btn btn-outline-light" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container steps-container" id="how">
  <div class="steps-text">
    <div class="steps-item">
      <h5>Cadastre-se</h5>
      <p>Cadastre-se e inclua sua experiência profissional e formação.</p>
    </div>
    <div class="steps-item">
      <h5>Escolha</h5>
      <p>Adicione as vagas de seu interesse à sua lista de vagas favoritas.</p>
    </div>
    <div class="steps-item">
      <h5>Pronto</h5>
      <p>As empresas interessadas entrarão em contato com você.</p>
    </div>
  </div>
  <div class="steps-picture" alt="VagaZap funciona em smartphones, tables e computadores.">
    <%= image_tag "thom-holmes-580122.jpg", class: "steps-img" %>
  </div>
</div>

<% if user_signed_in? %>
<% else %>
  <div class="free-start">
    <%= link_to "Cadastrar", new_user_registration_path, class: "btn-lg btn-primary" %>
  </div>
<% end %>

<div class="container features-container">
  <div class="features-cards">
    <div class="col-lg-4 features-box">
      <i class="fas fa-address-card"></i>
      <div class="features-card">
        <h5>Digital</h5>
        <p>Chega de andar por aí batendo de porta em porta com currículo de papel debaixo do braço.</p>
      </div>
    </div>
    <div class="col-lg-4 features-box">
      <i class="fas fa-map-marked-alt"></i>
      <div class="features-card">
        <h5>Prático</h5>
        <p>Você define a distância máxima para trabalhar e mostramos as vagas próximas a você.</p>
      </div>
    </div>
    <div class="col-lg-4 features-box">
      <i class="fas fa-user-check"></i>
      <div class="features-card">
        <h5>Simples</h5>
        <p>Sugerimos as vagas mais compatíveis com o seu perfil para você não perder tempo com filtros de busca.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="profile-box">

    <% if @user.degrees.empty? && @user.companies.empty? %>
      <p class="sub-header">Quer encontrar uma vaga adequada ao seu perfil?</p>
      <%= link_to "Completar perfil", new_degree_path, class: "btn btn-primary" %>
      <div class="separator">
      </div>
      <p class="sub-header">Representa uma empresa e quer contratar?</p>
      <%= link_to "Cadastrar empresa", new_company_path, class: "btn btn-secondary" %>
    <% else %>

      <h6>Ainda não foi possível encontrar uma vaga com o seu perfil.</h6>
      <!-- <h6>Obrigado por se cadastrar! As vagas estarão disponíveis a partir de 01 de Junho.</h6> -->
      <!-- <a href="mailto:marcus.maione@vagazap.com">Dúvidas ou sugestões: marcus.maione@vagazap.com</a> -->

      <% if @user.profile_incomplete? %>
        <br>
        <h6>Você precisa completar o seu perfil antes de continuar.</h6>
        <%= link_to "Completar perfil", edit_user_registration_path, class: "btn btn-primary" %>
      <% elsif @user.coordinates_incomplete? %>
        <br>
        <h6>Você precisa atualizar seu endereço no cadastro antes de continuar.</h6>
        <%= link_to "Atualizar endereço", edit_user_registration_path, class: "btn btn-primary" %>
      <% else %>
        <!-- Habilitar botão quando tiver vagas -->
        <%#= link_to "Vagas disponíveis", root_path, class: "btn btn-primary" %>

        <%= render 'user-details' %>
        <% if current_user.companies.count == 0 %>
          <%= render 'user-degrees', degrees: @degrees %>
          <%= render 'user-experiences', experiences: @experiences %>
          <%= render 'user-courses', courses: @courses %>
        <% else %>
          <%= render 'user-companies', companies: @companies %>
        <% end %>

      <% end %>
    <% end %>

  </div>
</div>