config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'profile', to: 'pages#profile'
  # Generic syntax:
  # verb 'path', to: 'controller#action', as: :route_name
  resources :users
  resources :degrees
  resources :experiences
  resources :courses
  resources :companies do
    resources :jobs do
      # resources :favorites
    end
  end
  post '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'favorites#create', :as => :favorite_create

  get '/companies/:company_id/jobs/:id/candidates', to: 'jobs#candidates', :as => :job_candidates
  get '/companies/:company_id/jobs/:id/candidate/:user_id', to: 'jobs#candidate', :as => :job_candidate

  get '/companies/:company_id/jobs/:id/favorites', to: 'jobs#favorites', :as => :job_favorites
end

app/models/company.rb
class Company < ApplicationRecord
  COMPANYSECTORS = ["Agricultura e Pecuária", "Alimentos e Bebidas", "Arquitetura e Engenharia",
                    "Arte e Cultura", "Beleza e Cosméticos", "Bares e Restaurantes",
                    "Call Center e Telemarketing", "Comércio Atacado", "Comércio Varejo",
                    "Construção", "Consultoria", "Design", "Enfermagem e Medicina", "Escolas e Cursos",
                    "Elétrico", "Fotografia e Vídeo", "Eventos", "Farmácia", "Hospedagem e Turismo",
                    "Imobiliário", "Jornalismo", "Laboratórios", "Limpeza", "Manutenção e Reparos",
                    "Marketing", "Mercados e Padarias", "Mercado Financeiro e de Capitais", "Mineração",
                    "Óleo e Gás", "Produção de Bens Duráveis", "Produção de Bens Não Duráveis",
                    "Programação e Desenvolvimento", "Publicidade e Propaganda",
                    "Segurança", "Seguros", "Serviços Gerais", "Siderurgia e Metalurgia",
                    "Tecnologia da Informação", "Telecomunicações", "Transporte Logística",
                    "Vestuário e Calçados"].freeze
  belongs_to :user
  has_many :jobs, :dependent => :destroy
  has_many :favorites, through: :jobs

  # def company_city
  #   if address.nil? || address == ""
  #     # 'Rio de Janeiro, Rio de Janeiro, Brazil'
  #   else
  #     address.split(', ')[1] + ', ' + address.split(', ')[2] + ', ' + address.split(', ')[3]
  #   end
  # end

  def name_incomplete?
    name.nil? || name == ''
  end

  def address_incomplete?
    address.nil? || address == ''
  end

  def sector_incomplete?
    sector.nil? || sector == ''
  end

  def phone_incomplete?
    phone.nil? || phone == ''
  end

  def coordinates_incomplete?
    latitude.nil?
  end

  def company_incomplete?
    name_incomplete? || address_incomplete? || sector_incomplete? || phone_incomplete? || coordinates_incomplete?
  end

  # geocoded_by :company_city
  # after_validation :geocode, if: :will_save_change_to_address?
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
  end

  def index
    @companies = policy_scope(Company)
  end

  def new
    @company = Company.new
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    @company.user = current_user
    authorize @company
    if @company.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @company.user = current_user
    if @company.update(company_params)
      redirect_to profile_path
    else
      render :update
    end
  end

  def destroy
    @company.destroy
    redirect_to profile_path
  end

  private

  def set_company
    @company = Company.find(params[:id])
    authorize @company
  end

  def company_params
    params.require(:company).permit(:name, :sector, :address, :phone, :address,
                                    :address_complement, :latitude, :longitute)
  end
end

app/views/companies/edit.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="form-box">

    <h5>Editar empresa:</h5>

    <%= simple_form_for(@company) do |f| %>

        <%= f.input :name,
                    required: true,
                    :label => "Nome da empresa:" %>
        <%= f.input :sector,
                    required: true,
                    :label => "Setor da empresa:",
                    collection: Company::COMPANYSECTORS %>
        <%= f.input :phone,
                    required: true,
                    hint: "Incluir DDD. Exemplo: (21)99999-9999.",
                    :label => "Telefone:" %>
        <%= f.input :address,
                    required: true,
                    hint: "IMPORTANTE: Apenas rua e número.",
                    :label => "Endereço (rua e número):" %>
        <%= f.input :address_complement,
                    hint: "Bloco, andar, sala, etc.",
                    :label => "Complemento:" %>

    <div class="form-actions">
      <%= f.submit class: 'btn btn-primary', value: "Confirmar" %>
    </div>
  <% end %>
      <br>
      <%= link_to "Voltar", profile_path, class: "btn btn-tertiary btn-sm" %>
      <br>
      <% if policy(@company).destroy? %>
        <%= link_to "Deletar esta empresa", company_path(@company),
            method: :delete, class: "edit-remove" %>
      <% end %>
  </div>
</div>

app/views/companies/new.html.erb
<div class="container col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="form-box">

   <h5>Cadastrar empresa:</h5>

   <%= simple_form_for(@company) do |f| %>

        <%= f.input :name,
                    required: true,
                    :label => "Nome da empresa:" %>
        <%= f.input :sector,
                    required: true,
                    :label => "Setor da empresa:",
                    collection: Company::COMPANYSECTORS %>
        <%= f.input :phone,
                    required: true,
                    hint: "Incluir DDD. Exemplo: (21)99999-9999.",
                    :label => "Telefone:" %>
        <%= f.input :address,
                    required: true,
                    hint: "IMPORTANTE: Apenas rua e número.",
                    :label => "Endereço (rua e número):" %>
        <%= f.input :address_complement,
                    hint: "Bloco, andar, sala, etc.",
                    :label => "Complemento:" %>

   <div class="form-actions">
     <%= f.submit class: 'btn btn-primary', value: "Confirmar" %>
   </div>
   <% end %>

   <p>Você pode cadastrar mais empresas depois se quiser.</p>

  </div>
</div>